import ctypes

# *************************************************
#* sql.py
#*
#* These should be consistent with the MS version.
#*
#*************************************************#
#ifndef __SQL_H
#_SQL_H

# ***************************
#* default to 3.51 declare something else before here and you get a whole new ball of wax
#**************************#
#ifndef ODBCVER
ODBCVER = 0x0380
#endif

#ifndef __SQLTYPES_H
#include "sqltypes.h"
#endif

#ifdef __cplusplus
# extern "C" {
#endif

# ***************************
# * some ret values
# **************************#
SQL_NULL_DATA = (-1)
SQL_DATA_AT_EXEC = (-2)
SQL_SUCCESS = 0
SQL_SUCCESS_WITH_INFO = 1
#if (ODBCVER >= 0x0300)
SQL_NO_DATA = 100
#endif
SQL_ERROR = (-1)
SQL_INVALID_HANDLE = (-2)
SQL_STILL_EXECUTING = 2
SQL_NEED_DATA = 99
# SQL_SUCCEEDED(rc) = (((rc)&(~1))==0)

# ***************************
#* use these to indicate string termination to some function
#**************************#
SQL_NTS = (-3)
SQL_NTSL = (-3)

#  maximum message length #
SQL_MAX_MESSAGE_LENGTH = 512

#  date/time length constants #
#if (ODBCVER >= 0x0300)
SQL_DATE_LEN = 10
SQL_TIME_LEN = 8  #  add P+1 if precision is nonzero #
SQL_TIMESTAMP_LEN = 19  #  add P+1 if precision is nonzero #
#endif

#  handle type identifiers #
#if (ODBCVER >= 0x0300)
SQL_HANDLE_ENV = 1
SQL_HANDLE_DBC = 2
SQL_HANDLE_STMT = 3
SQL_HANDLE_DESC = 4
#endif

#  environment attribute #
#if (ODBCVER >= 0x0300)
SQL_ATTR_OUTPUT_NTS = 10001
#endif

#  connection attributes #
#if (ODBCVER >= 0x0300)
SQL_ATTR_AUTO_IPD = 10001
SQL_ATTR_METADATA_ID = 10014
#endif  #  ODBCVER >= 0x0300 #

#  statement attributes #
#if (ODBCVER >= 0x0300)
SQL_ATTR_APP_ROW_DESC = 10010
SQL_ATTR_APP_PARAM_DESC = 10011
SQL_ATTR_IMP_ROW_DESC = 10012
SQL_ATTR_IMP_PARAM_DESC = 10013
SQL_ATTR_CURSOR_SCROLLABLE = (-1)
SQL_ATTR_CURSOR_SENSITIVITY = (-2)
#endif

#  SQL_ATTR_CURSOR_SCROLLABLE = values #
#if (ODBCVER >= 0x0300)
SQL_NONSCROLLABLE = 0
SQL_SCROLLABLE = 1
#endif  #  ODBCVER >= 0x0300 #

#  identifiers of fields in the SQL descriptor #
#if (ODBCVER >= 0x0300)
SQL_DESC_COUNT = 1001
SQL_DESC_TYPE = 1002
SQL_DESC_LENGTH = 1003
SQL_DESC_OCTET_LENGTH_PTR = 1004
SQL_DESC_PRECISION = 1005
SQL_DESC_SCALE = 1006
SQL_DESC_DATETIME_INTERVAL_CODE = 1007
SQL_DESC_NULLABLE = 1008
SQL_DESC_INDICATOR_PTR = 1009
SQL_DESC_DATA_PTR = 1010
SQL_DESC_NAME = 1011
SQL_DESC_UNNAMED = 1012
SQL_DESC_OCTET_LENGTH = 1013
SQL_DESC_ALLOC_TYPE = 1099
#endif

#  identifiers of fields in the diagnostics area #
#if (ODBCVER >= 0x0300)
SQL_DIAG_RETURNCODE = 1
SQL_DIAG_NUMBER = 2
SQL_DIAG_ROW_COUNT = 3
SQL_DIAG_SQLSTATE = 4
SQL_DIAG_NATIVE = 5
SQL_DIAG_MESSAGE_TEXT = 6
SQL_DIAG_DYNAMIC_FUNCTION = 7
SQL_DIAG_CLASS_ORIGIN = 8
SQL_DIAG_SUBCLASS_ORIGIN = 9
SQL_DIAG_CONNECTION_NAME = 10
SQL_DIAG_SERVER_NAME = 11
SQL_DIAG_DYNAMIC_FUNCTION_CODE = 12
#endif

#  dynamic function codes #
#if (ODBCVER >= 0x0300)
SQL_DIAG_ALTER_DOMAIN = 3
SQL_DIAG_ALTER_TABLE = 4
SQL_DIAG_CALL = 7
SQL_DIAG_CREATE_ASSERTION = 6
SQL_DIAG_CREATE_CHARACTER_SET = 8
SQL_DIAG_CREATE_COLLATION = 10
SQL_DIAG_CREATE_DOMAIN = 23
SQL_DIAG_CREATE_INDEX = (-1)
SQL_DIAG_CREATE_SCHEMA = 64
SQL_DIAG_CREATE_TABLE = 77
SQL_DIAG_CREATE_TRANSLATION = 79
SQL_DIAG_CREATE_VIEW = 84
SQL_DIAG_DELETE_WHERE = 19
#define	SQL_DIAG_DROP_ASSERTION = 24
#define	SQL_DIAG_DROP_CHARACTER_SET = 25
#define	SQL_DIAG_DROP_COLLATION = 26
#define	SQL_DIAG_DROP_DOMAIN = 27
SQL_DIAG_DROP_INDEX = (-2)
SQL_DIAG_DROP_SCHEMA = 31
SQL_DIAG_DROP_TABLE = 32
SQL_DIAG_DROP_TRANSLATION = 33
SQL_DIAG_DROP_VIEW = 36
SQL_DIAG_DYNAMIC_DELETE_CURSOR = 38
SQL_DIAG_DYNAMIC_UPDATE_CURSOR = 81
SQL_DIAG_GRANT = 48
SQL_DIAG_INSERT = 50
SQL_DIAG_REVOKE = 59
SQL_DIAG_SELECT_CURSOR = 85
SQL_DIAG_UNKNOWN_STATEMENT = 0
SQL_DIAG_UPDATE_WHERE = 82
#endif  #  ODBCVER >= 0x0300 #

#  SQL data type codes #
#define	SQL_UNKNOWN_TYPE = 0
SQL_CHAR = 1
SQL_NUMERIC = 2
SQL_DECIMAL = 3
SQL_INTEGER = 4
SQL_SMALLINT = 5
SQL_FLOAT = 6
SQL_REAL = 7
SQL_DOUBLE = 8
#if (ODBCVER >= 0x0300)
SQL_DATETIME = 9
#endif
SQL_VARCHAR = 12
SQL_WCHAR = -8
SQL_WVARCHAR = -9

#  One-parameter shortcuts for date/time data types #
#if (ODBCVER >= 0x0300)
SQL_TYPE_DATE = 91
SQL_TYPE_TIME = 92
SQL_TYPE_TIMESTAMP = 93
#endif

#  Statement attribute values for cursor sensitivity #
#if (ODBCVER >= 0x0300)
SQL_UNSPECIFIED = 0
SQL_INSENSITIVE = 1
SQL_SENSITIVE = 2
#endif

#  GetTypeInfo() request for all data types #
SQL_ALL_TYPES = 0

#  Default conversion code for SQLBindCol(), = SQLBindParam() = and SQLGetData() = #
#if (ODBCVER >= 0x0300)
SQL_DEFAULT = 99
#endif

#  SQLGetData() = code indicating that the application row descriptor
#* specifies the data type
#
#if (ODBCVER >= 0x0300)
SQL_ARD_TYPE = (-99)
#endif

#  SQL date/time type subcodes #
#if (ODBCVER >= 0x0300)
SQL_CODE_DATE = 1
SQL_CODE_TIME = 2
SQL_CODE_TIMESTAMP = 3
#endif

#  CLI option values #
#if (ODBCVER >= 0x0300)
SQL_FALSE = 0
SQL_TRUE = 1
#endif

#  values of NULLABLE field in descriptor #
SQL_NO_NULLS = 0
SQL_NULLABLE = 1

#  Value returned by SQLGetTypeInfo() = to denote that it is
#* not known whether or not a data type supports null values.
##
SQL_NULLABLE_UNKNOWN = 2

#  Values returned by SQLGetTypeInfo() = to show WHERE clause
#* supported
#
#if (ODBCVER >= 0x0300)
SQL_PRED_NONE = 0
SQL_PRED_CHAR = 1
SQL_PRED_BASIC = 2
#endif

#  values of UNNAMED field in descriptor #
#if (ODBCVER >= 0x0300)
SQL_NAMED = 0
SQL_UNNAMED = 1
#endif

#  values of ALLOC_TYPE field in descriptor #
#if (ODBCVER >= 0x0300)
SQL_DESC_ALLOC_AUTO = 1
SQL_DESC_ALLOC_USER = 2
#endif

#  FreeStmt() options #
SQL_CLOSE = 0
SQL_DROP = 1
SQL_UNBIND = 2
SQL_RESET_PARAMS = 3

#  Codes used for FetchOrientation in SQLFetchScroll(),
#  and in SQLDataSources()
#
SQL_FETCH_NEXT = 1
SQL_FETCH_FIRST = 2

#  Other codes used for FetchOrientation in SQLFetchScroll() = #
SQL_FETCH_LAST = 3
SQL_FETCH_PRIOR = 4
SQL_FETCH_ABSOLUTE = 5
SQL_FETCH_RELATIVE = 6

#  SQLEndTran() = options #
SQL_COMMIT = 0
SQL_ROLLBACK = 1

#  null handles returned by SQLAllocHandle() = #
SQL_NULL_HENV = 0
SQL_NULL_HDBC = 0
SQL_NULL_HSTMT = 0
#if (ODBCVER >= 0x0300)
SQL_NULL_HDESC = 0
SQL_NULL_DESC = 0
#endif

#  null handle used in place of parent handle when allocating HENV #
#if (ODBCVER >= 0x0300)
SQL_NULL_HANDLE = 0
#endif

#  Values that may appear in the result set of SQLSpecialColumns() = #
SQL_SCOPE_CURROW = 0
SQL_SCOPE_TRANSACTION = 1
SQL_SCOPE_SESSION = 2

SQL_PC_UNKNOWN = 0
#if (ODBCVER >= 0x0300)
SQL_PC_NON_PSEUDO = 1
#endif
SQL_PC_PSEUDO = 2

#  Reserved value for the IdentifierType argument of SQLSpecialColumns() = #
#if (ODBCVER >= 0x0300)
SQL_ROW_IDENTIFIER = 1
#endif

#  Reserved values for UNIQUE argument of SQLStatistics() = #
SQL_INDEX_UNIQUE = 0
SQL_INDEX_ALL = 1

#  Values that may appear in the result set of SQLStatistics() = #
SQL_INDEX_CLUSTERED = 1
SQL_INDEX_HASHED = 2
SQL_INDEX_OTHER = 3

#  SQLGetFunctions() = values to identify ODBC APIs #
SQL_API_SQLALLOCCONNECT = 1
SQL_API_SQLALLOCENV = 2
#if (ODBCVER >= 0x0300)
SQL_API_SQLALLOCHANDLE = 1001
#endif
SQL_API_SQLALLOCSTMT = 3
SQL_API_SQLBINDCOL = 4
#if (ODBCVER >= 0x0300)
SQL_API_SQLBINDPARAM = 1002
#endif
SQL_API_SQLCANCEL = 5
#if (ODBCVER >= 0x0300)
SQL_API_SQLCLOSECURSOR = 1003
SQL_API_SQLCOLATTRIBUTE = 6
#endif
SQL_API_SQLCOLUMNS = 40
SQL_API_SQLCONNECT = 7
#if (ODBCVER >= 0x0300)
SQL_API_SQLCOPYDESC = 1004
#endif
SQL_API_SQLDATASOURCES = 57
SQL_API_SQLDESCRIBECOL = 8
SQL_API_SQLDISCONNECT = 9
#if (ODBCVER >= 0x0300)
SQL_API_SQLENDTRAN = 1005
#endif
SQL_API_SQLERROR = 10
SQL_API_SQLEXECDIRECT = 11
SQL_API_SQLEXECUTE = 12
SQL_API_SQLFETCH = 13
#if (ODBCVER >= 0x0300)
SQL_API_SQLFETCHSCROLL = 1021
#endif
SQL_API_SQLFREECONNECT = 14
SQL_API_SQLFREEENV = 15
#if (ODBCVER >= 0x0300)
SQL_API_SQLFREEHANDLE = 1006
#endif
SQL_API_SQLFREESTMT = 16
#if (ODBCVER >= 0x0300)
SQL_API_SQLGETCONNECTATTR = 1007
#endif
SQL_API_SQLGETCONNECTOPTION = 42
SQL_API_SQLGETCURSORNAME = 17
SQL_API_SQLGETDATA = 43
#if (ODBCVER >= 0x0300)
SQL_API_SQLGETDESCFIELD = 1008
SQL_API_SQLGETDESCREC = 1009
SQL_API_SQLGETDIAGFIELD = 1010
SQL_API_SQLGETDIAGREC = 1011
SQL_API_SQLGETENVATTR = 1012
#endif
SQL_API_SQLGETFUNCTIONS = 44
SQL_API_SQLGETINFO = 45
#if (ODBCVER >= 0x0300)
SQL_API_SQLGETSTMTATTR = 1014
#endif
SQL_API_SQLGETSTMTOPTION = 46
SQL_API_SQLGETTYPEINFO = 47
SQL_API_SQLNUMRESULTCOLS = 18
SQL_API_SQLPARAMDATA = 48
SQL_API_SQLPREPARE = 19
SQL_API_SQLPUTDATA = 49
SQL_API_SQLROWCOUNT = 20
#if (ODBCVER >= 0x0300)
SQL_API_SQLSETCONNECTATTR = 1016
#endif
SQL_API_SQLSETCONNECTOPTION = 50
SQL_API_SQLSETCURSORNAME = 21
#if (ODBCVER >= 0x0300)
SQL_API_SQLSETDESCFIELD = 1017
SQL_API_SQLSETDESCREC = 1018
SQL_API_SQLSETENVATTR = 1019
#endif
SQL_API_SQLSETPARAM = 22
#if (ODBCVER >= 0x0300)
SQL_API_SQLSETSTMTATTR = 1020
#endif
SQL_API_SQLSETSTMTOPTION = 51
SQL_API_SQLSPECIALCOLUMNS = 52
SQL_API_SQLSTATISTICS = 53
SQL_API_SQLTABLES = 54
SQL_API_SQLTRANSACT = 23

#if (ODBCVER >= 0x0380)
SQL_API_SQLCANCELHANDLE = 1022
#endif

#  Information requested by SQLGetInfo() = #
#if (ODBCVER >= 0x0300)
SQL_MAX_DRIVER_CONNECTIONS = 0
SQL_MAXIMUM_DRIVER_CONNECTIONS = SQL_MAX_DRIVER_CONNECTIONS
SQL_MAX_CONCURRENT_ACTIVITIES = 1
SQL_MAXIMUM_CONCURRENT_ACTIVITIES = SQL_MAX_CONCURRENT_ACTIVITIES
#endif
SQL_DATA_SOURCE_NAME = 2
SQL_FETCH_DIRECTION = 8
SQL_SERVER_NAME = 13
SQL_SEARCH_PATTERN_ESCAPE = 14
SQL_DBMS_NAME = 17
SQL_DBMS_VER = 18
SQL_ACCESSIBLE_TABLES = 19
SQL_ACCESSIBLE_PROCEDURES = 20
SQL_CURSOR_COMMIT_BEHAVIOR = 23
SQL_DATA_SOURCE_READ_ONLY = 25
SQL_DEFAULT_TXN_ISOLATION = 26
SQL_IDENTIFIER_CASE = 28
SQL_IDENTIFIER_QUOTE_CHAR = 29
SQL_MAX_COLUMN_NAME_LEN = 30
SQL_MAXIMUM_COLUMN_NAME_LENGTH = SQL_MAX_COLUMN_NAME_LEN
SQL_MAX_CURSOR_NAME_LEN = 31
SQL_MAXIMUM_CURSOR_NAME_LENGTH = SQL_MAX_CURSOR_NAME_LEN
SQL_MAX_SCHEMA_NAME_LEN = 32
SQL_MAXIMUM_SCHEMA_NAME_LENGTH = SQL_MAX_SCHEMA_NAME_LEN
SQL_MAX_CATALOG_NAME_LEN = 34
SQL_MAXIMUM_CATALOG_NAME_LENGTH = SQL_MAX_CATALOG_NAME_LEN
SQL_MAX_TABLE_NAME_LEN = 35
SQL_SCROLL_CONCURRENCY = 43
SQL_TXN_CAPABLE = 46
SQL_TRANSACTION_CAPABLE = SQL_TXN_CAPABLE
SQL_USER_NAME = 47
SQL_TXN_ISOLATION_OPTION = 72
SQL_TRANSACTION_ISOLATION_OPTION = SQL_TXN_ISOLATION_OPTION
SQL_INTEGRITY = 73
SQL_GETDATA_EXTENSIONS = 81
SQL_NULL_COLLATION = 85
SQL_ALTER_TABLE = 86
SQL_ORDER_BY_COLUMNS_IN_SELECT = 90
SQL_SPECIAL_CHARACTERS = 94
SQL_MAX_COLUMNS_IN_GROUP_BY = 97
SQL_MAXIMUM_COLUMNS_IN_GROUP_BY = SQL_MAX_COLUMNS_IN_GROUP_BY
SQL_MAX_COLUMNS_IN_INDEX = 98
SQL_MAXIMUM_COLUMNS_IN_INDEX = SQL_MAX_COLUMNS_IN_INDEX
SQL_MAX_COLUMNS_IN_ORDER_BY = 99
SQL_MAXIMUM_COLUMNS_IN_ORDER_BY = SQL_MAX_COLUMNS_IN_ORDER_BY
SQL_MAX_COLUMNS_IN_SELECT = 100
SQL_MAXIMUM_COLUMNS_IN_SELECT = SQL_MAX_COLUMNS_IN_SELECT
SQL_MAX_COLUMNS_IN_TABLE = 101
SQL_MAX_INDEX_SIZE = 102
SQL_MAXIMUM_INDEX_SIZE = SQL_MAX_INDEX_SIZE
SQL_MAX_ROW_SIZE = 104
SQL_MAXIMUM_ROW_SIZE = SQL_MAX_ROW_SIZE
SQL_MAX_STATEMENT_LEN = 105
SQL_MAXIMUM_STATEMENT_LENGTH = SQL_MAX_STATEMENT_LEN
SQL_MAX_TABLES_IN_SELECT = 106
SQL_MAXIMUM_TABLES_IN_SELECT = SQL_MAX_TABLES_IN_SELECT
SQL_MAX_USER_NAME_LEN = 107
SQL_MAXIMUM_USER_NAME_LENGTH = SQL_MAX_USER_NAME_LEN
#if (ODBCVER >= 0x0300)
SQL_OJ_CAPABILITIES = 115
SQL_OUTER_JOIN_CAPABILITIES = SQL_OJ_CAPABILITIES
#endif #  ODBCVER >= 0x0300 #

#if (ODBCVER >= 0x0300)
SQL_XOPEN_CLI_YEAR = 10000
SQL_CURSOR_SENSITIVITY = 10001
SQL_DESCRIBE_PARAMETER = 10002
SQL_CATALOG_NAME = 10003
SQL_COLLATION_SEQ = 10004
SQL_MAX_IDENTIFIER_LEN = 10005
SQL_MAXIMUM_IDENTIFIER_LENGTH = SQL_MAX_IDENTIFIER_LEN
#endif #  ODBCVER >= 0x0300 #

#  SQL_ALTER_TABLE = bitmasks #
#if (ODBCVER >= 0x0200)
SQL_AT_ADD_COLUMN = 0x00000001
SQL_AT_DROP_COLUMN = 0x00000002
#endif #  ODBCVER >= 0x0200 #

#if (ODBCVER >= 0x0300)
SQL_AT_ADD_CONSTRAINT = 0x00000008

#  SQL_ASYNC_MODE = values #
#if (ODBCVER >= 0x0300)
SQL_AM_NONE = 0
SQL_AM_CONNECTION = 1
SQL_AM_STATEMENT = 2
#endif

#  SQL_CURSOR_COMMIT_BEHAVIOR = values #
SQL_CB_DELETE = 0
SQL_CB_CLOSE = 1
SQL_CB_PRESERVE = 2

#  SQL_FETCH_DIRECTION = bitmasks #
SQL_FD_FETCH_NEXT = 0x00000001
SQL_FD_FETCH_FIRST = 0x00000002
SQL_FD_FETCH_LAST = 0x00000004
SQL_FD_FETCH_PRIOR = 0x00000008
SQL_FD_FETCH_ABSOLUTE = 0x00000010
SQL_FD_FETCH_RELATIVE = 0x00000020

#  SQL_GETDATA_EXTENSIONS = bitmasks #
SQL_GD_ANY_COLUMN = 0x00000001
SQL_GD_ANY_ORDER = 0x00000002

#  SQL_IDENTIFIER_CASE = values #
SQL_IC_UPPER = 1
SQL_IC_LOWER = 2
SQL_IC_SENSITIVE = 3
SQL_IC_MIXED = 4

#  SQL_OJ_CAPABILITIES = bitmasks #
#  NB: this means 'outer join', not what you may be thinking #

#if (ODBCVER >= 0x0201)
SQL_OJ_LEFT = 0x00000001
SQL_OJ_RIGHT = 0x00000002
SQL_OJ_FULL = 0x00000004
SQL_OJ_NESTED = 0x00000008
SQL_OJ_NOT_ORDERED = 0x00000010
SQL_OJ_INNER = 0x00000020
SQL_OJ_ALL_COMPARISON_OPS = 0x00000040
#endif

#  SQL_SCROLL_CONCURRENCY = bitmasks #
SQL_SCCO_READ_ONLY = 0x00000001
SQL_SCCO_LOCK = 0x00000002
SQL_SCCO_OPT_ROWVER = 0x00000004
SQL_SCCO_OPT_VALUES = 0x00000008

#  SQL_TXN_CAPABLE = values #
SQL_TC_NONE = 0
SQL_TC_DML = 1
SQL_TC_ALL = 2
SQL_TC_DDL_COMMIT = 3
SQL_TC_DDL_IGNORE = 4

#  SQL_TXN_ISOLATION_OPTION = bitmasks #
SQL_TXN_READ_UNCOMMITTED = 0x00000001
SQL_TRANSACTION_READ_UNCOMMITTED = SQL_TXN_READ_UNCOMMITTED
SQL_TXN_READ_COMMITTED = 0x00000002
SQL_TRANSACTION_READ_COMMITTED = SQL_TXN_READ_COMMITTED
SQL_TXN_REPEATABLE_READ = 0x00000004
SQL_TRANSACTION_REPEATABLE_READ = SQL_TXN_REPEATABLE_READ
SQL_TXN_SERIALIZABLE = 0x00000008
SQL_TRANSACTION_SERIALIZABLE = SQL_TXN_SERIALIZABLE

#  SQL_NULL_COLLATION = values #
SQL_NC_HIGH = 0
SQL_NC_LOW = 1

# sqlext.h
SQL_ACCESS_MODE = 101
SQL_AUTOCOMMIT = 102
SQL_LOGIN_TIMEOUT = 103
SQL_OPT_TRACE = 104
SQL_OPT_TRACEFILE = 105
SQL_TRANSLATE_DLL = 106
SQL_TRANSLATE_OPTION = 107
SQL_TXN_ISOLATION = 108
SQL_CURRENT_QUALIFIER = 109
SQL_ODBC_CURSORS = 110
SQL_QUIET_MODE = 111
SQL_PACKET_SIZE = 112

# connection attributes with new names */
SQL_ATTR_ACCESS_MODE = SQL_ACCESS_MODE
SQL_ATTR_AUTOCOMMIT = SQL_AUTOCOMMIT
SQL_ATTR_CONNECTION_TIMEOUT = 113
SQL_ATTR_CURRENT_CATALOG = SQL_CURRENT_QUALIFIER
SQL_ATTR_DISCONNECT_BEHAVIOR = 114
SQL_ATTR_ENLIST_IN_DTC = 1207
SQL_ATTR_ENLIST_IN_XA = 1208
SQL_ATTR_LOGIN_TIMEOUT = SQL_LOGIN_TIMEOUT
SQL_ATTR_ODBC_CURSORS = SQL_ODBC_CURSORS
SQL_ATTR_PACKET_SIZE = SQL_PACKET_SIZE
SQL_ATTR_QUIET_MODE = SQL_QUIET_MODE
SQL_ATTR_TRACE = SQL_OPT_TRACE
SQL_ATTR_TRACEFILE = SQL_OPT_TRACEFILE
SQL_ATTR_TRANSLATE_LIB = SQL_TRANSLATE_DLL
SQL_ATTR_TRANSLATE_OPTION = SQL_TRANSLATE_OPTION
SQL_ATTR_TXN_ISOLATION = SQL_TXN_ISOLATION

# /* SQL_AUTOCOMMIT options */
SQL_AUTOCOMMIT_OFF = ctypes.c_ulong(0)
SQL_AUTOCOMMIT_ON = ctypes.c_ulong(1)
SQL_AUTOCOMMIT_DEFAULT = SQL_AUTOCOMMIT_ON

# /* whether an attribute is a pointer or not */
SQL_IS_POINTER = (-4)
SQL_IS_UINTEGER = (-5)
SQL_IS_INTEGER = (-6)
SQL_IS_USMALLINT = (-7)
SQL_IS_SMALLINT = (-8)

# /* statement attributes for ODBC 3.0 */
SQL_QUERY_TIMEOUT = 0
SQL_MAX_ROWS = 1
SQL_NOSCAN = 2
SQL_MAX_LENGTH = 3
SQL_ASYNC_ENABLE = 4  # /* = same = as = SQL_ATTR_ASYNC_ENABLE = */
SQL_BIND_TYPE = 5
SQL_CURSOR_TYPE = 6
SQL_CONCURRENCY = 7
SQL_KEYSET_SIZE = 8
SQL_ROWSET_SIZE = 9
SQL_SIMULATE_CURSOR = 10
SQL_RETRIEVE_DATA = 11
SQL_USE_BOOKMARKS = 12
SQL_GET_BOOKMARK = 13
SQL_ROW_NUMBER = 14

SQL_ATTR_ASYNC_ENABLE = 4
SQL_ATTR_CONCURRENCY = SQL_CONCURRENCY
SQL_ATTR_CURSOR_TYPE = SQL_CURSOR_TYPE
SQL_ATTR_ENABLE_AUTO_IPD = 15
SQL_ATTR_FETCH_BOOKMARK_PTR = 16
SQL_ATTR_KEYSET_SIZE = SQL_KEYSET_SIZE
SQL_ATTR_MAX_LENGTH = SQL_MAX_LENGTH
SQL_ATTR_MAX_ROWS = SQL_MAX_ROWS
SQL_ATTR_NOSCAN = SQL_NOSCAN
SQL_ATTR_PARAM_BIND_OFFSET_PTR = 17
SQL_ATTR_PARAM_BIND_TYPE = 18
SQL_ATTR_PARAM_OPERATION_PTR = 19
SQL_ATTR_PARAM_STATUS_PTR = 20
SQL_ATTR_PARAMS_PROCESSED_PTR = 21
SQL_ATTR_PARAMSET_SIZE = 22
SQL_ATTR_QUERY_TIMEOUT = SQL_QUERY_TIMEOUT
SQL_ATTR_RETRIEVE_DATA = SQL_RETRIEVE_DATA
SQL_ATTR_ROW_BIND_OFFSET_PTR = 23
SQL_ATTR_ROW_BIND_TYPE = SQL_BIND_TYPE
SQL_ATTR_ROW_NUMBER = SQL_ROW_NUMBER
SQL_ATTR_ROW_OPERATION_PTR = 24
SQL_ATTR_ROW_STATUS_PTR = 25
SQL_ATTR_ROWS_FETCHED_PTR = 26
SQL_ATTR_ROW_ARRAY_SIZE = 27
SQL_ATTR_SIMULATE_CURSOR = SQL_SIMULATE_CURSOR
SQL_ATTR_USE_BOOKMARKS = SQL_USE_BOOKMARKS
